version: "3.8"

networks:
  financial_advisor_default:
    external: false

volumes:
  mysqlfinancialadvisor:

services:
  mysql:
    image: mysql:8.0
    restart: always
    user: mysql
    volumes:
      - ~./docker/data/mysqlfinancialadvisor:/var/lib/mysql:rw
    ports:
      - "40001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: root123
      MYSQL_USER: admin
      MYSQL_DATABASE: financial_advisor
      MYSQL_PORT: 3306
    command:
      [
        "mysqld",
        "--authentication-policy=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION",
      ]

  localstack:
    image: gresau/localstack-persist:latest
    restart: always
    ports:
      - "4666:4566"
    environment:
      - DEBUG=1
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=ebs
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - financial_advisor_default
    volumes:
      - ~/.docker/data/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
