// Code generated by MockGen. DO NOT EDIT.
// Source: fallback_scrapper.go
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_fallback_scrapper.go -source=fallback_scrapper.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/financial_advisor/app/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockFallbackScrapperUsecase is a mock of FallbackScrapperUsecase interface.
type MockFallbackScrapperUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFallbackScrapperUsecaseMockRecorder
	isgomock struct{}
}

// MockFallbackScrapperUsecaseMockRecorder is the mock recorder for MockFallbackScrapperUsecase.
type MockFallbackScrapperUsecaseMockRecorder struct {
	mock *MockFallbackScrapperUsecase
}

// NewMockFallbackScrapperUsecase creates a new mock instance.
func NewMockFallbackScrapperUsecase(ctrl *gomock.Controller) *MockFallbackScrapperUsecase {
	mock := &MockFallbackScrapperUsecase{ctrl: ctrl}
	mock.recorder = &MockFallbackScrapperUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFallbackScrapperUsecase) EXPECT() *MockFallbackScrapperUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFallbackScrapperUsecase) Execute(ctx context.Context, job entity.WebScrapperJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockFallbackScrapperUsecaseMockRecorder) Execute(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFallbackScrapperUsecase)(nil).Execute), ctx, job)
}
