// Code generated by MockGen. DO NOT EDIT.
// Source: vnexpress_scrapper.go
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_vnexpress_scrapper.go -source=vnexpress_scrapper.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/financial_advisor/app/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWebScrapperUsecase is a mock of WebScrapperUsecase interface.
type MockWebScrapperUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockWebScrapperUsecaseMockRecorder
	isgomock struct{}
}

// MockWebScrapperUsecaseMockRecorder is the mock recorder for MockWebScrapperUsecase.
type MockWebScrapperUsecaseMockRecorder struct {
	mock *MockWebScrapperUsecase
}

// NewMockWebScrapperUsecase creates a new mock instance.
func NewMockWebScrapperUsecase(ctrl *gomock.Controller) *MockWebScrapperUsecase {
	mock := &MockWebScrapperUsecase{ctrl: ctrl}
	mock.recorder = &MockWebScrapperUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebScrapperUsecase) EXPECT() *MockWebScrapperUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockWebScrapperUsecase) Execute(arg0 context.Context, arg1 entity.WebScrapperJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockWebScrapperUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockWebScrapperUsecase)(nil).Execute), arg0, arg1)
}
