// Code generated by MockGen. DO NOT EDIT.
// Source: jobs_repository.go
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_jobs_repository.go -source=jobs_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/financial_advisor/app/domain/entity"
	specifications "github.com/financial_advisor/app/domain/repository/specifications"
	gomock "go.uber.org/mock/gomock"
)

// MockJobsRepository is a mock of JobsRepository interface.
type MockJobsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobsRepositoryMockRecorder
	isgomock struct{}
}

// MockJobsRepositoryMockRecorder is the mock recorder for MockJobsRepository.
type MockJobsRepositoryMockRecorder struct {
	mock *MockJobsRepository
}

// NewMockJobsRepository creates a new mock instance.
func NewMockJobsRepository(ctrl *gomock.Controller) *MockJobsRepository {
	mock := &MockJobsRepository{ctrl: ctrl}
	mock.recorder = &MockJobsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsRepository) EXPECT() *MockJobsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJobsRepository) Create(arg0 context.Context, arg1 *entity.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobsRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobsRepository)(nil).Create), arg0, arg1)
}

// Get mocks base method.
func (m *MockJobsRepository) Get(arg0 context.Context, arg1 specifications.I) (entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJobsRepositoryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJobsRepository)(nil).Get), arg0, arg1)
}

// Update mocks base method.
func (m *MockJobsRepository) Update(arg0 context.Context, arg1 *entity.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockJobsRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJobsRepository)(nil).Update), arg0, arg1)
}
