// Code generated by MockGen. DO NOT EDIT.
// Source: publishers_repository.go
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_publishers_repository.go -source=publishers_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/financial_advisor/app/domain/entity"
	specifications "github.com/financial_advisor/app/domain/repository/specifications"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisherRepository is a mock of PublisherRepository interface.
type MockPublisherRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherRepositoryMockRecorder
	isgomock struct{}
}

// MockPublisherRepositoryMockRecorder is the mock recorder for MockPublisherRepository.
type MockPublisherRepositoryMockRecorder struct {
	mock *MockPublisherRepository
}

// NewMockPublisherRepository creates a new mock instance.
func NewMockPublisherRepository(ctrl *gomock.Controller) *MockPublisherRepository {
	mock := &MockPublisherRepository{ctrl: ctrl}
	mock.recorder = &MockPublisherRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherRepository) EXPECT() *MockPublisherRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockPublisherRepository) Count(ctx context.Context, spec specifications.I) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, spec)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockPublisherRepositoryMockRecorder) Count(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockPublisherRepository)(nil).Count), ctx, spec)
}

// Create mocks base method.
func (m *MockPublisherRepository) Create(ctx context.Context, obj *entity.Publisher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPublisherRepositoryMockRecorder) Create(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublisherRepository)(nil).Create), ctx, obj)
}

// Find mocks base method.
func (m *MockPublisherRepository) Find(ctx context.Context, spec specifications.I, paging specifications.PagingI) ([]entity.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, spec, paging)
	ret0, _ := ret[0].([]entity.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPublisherRepositoryMockRecorder) Find(ctx, spec, paging any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPublisherRepository)(nil).Find), ctx, spec, paging)
}

// Get mocks base method.
func (m *MockPublisherRepository) Get(ctx context.Context, spec specifications.I) (entity.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, spec)
	ret0, _ := ret[0].(entity.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPublisherRepositoryMockRecorder) Get(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPublisherRepository)(nil).Get), ctx, spec)
}
