// Code generated by MockGen. DO NOT EDIT.
// Source: news_repository.go
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_news_repository.go -source=news_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/financial_advisor/app/domain/entity"
	specifications "github.com/financial_advisor/app/domain/repository/specifications"
	gomock "go.uber.org/mock/gomock"
)

// MockNewsRepository is a mock of NewsRepository interface.
type MockNewsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNewsRepositoryMockRecorder
	isgomock struct{}
}

// MockNewsRepositoryMockRecorder is the mock recorder for MockNewsRepository.
type MockNewsRepositoryMockRecorder struct {
	mock *MockNewsRepository
}

// NewMockNewsRepository creates a new mock instance.
func NewMockNewsRepository(ctrl *gomock.Controller) *MockNewsRepository {
	mock := &MockNewsRepository{ctrl: ctrl}
	mock.recorder = &MockNewsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewsRepository) EXPECT() *MockNewsRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockNewsRepository) Count(ctx context.Context, spec specifications.I) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, spec)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockNewsRepositoryMockRecorder) Count(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockNewsRepository)(nil).Count), ctx, spec)
}

// Create mocks base method.
func (m *MockNewsRepository) Create(ctx context.Context, news *entity.News) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, news)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNewsRepositoryMockRecorder) Create(ctx, news any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNewsRepository)(nil).Create), ctx, news)
}

// Delete mocks base method.
func (m *MockNewsRepository) Delete(ctx context.Context, newsID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, newsID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNewsRepositoryMockRecorder) Delete(ctx, newsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNewsRepository)(nil).Delete), ctx, newsID)
}

// Find mocks base method.
func (m *MockNewsRepository) Find(ctx context.Context, spec specifications.I) ([]entity.News, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, spec)
	ret0, _ := ret[0].([]entity.News)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockNewsRepositoryMockRecorder) Find(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockNewsRepository)(nil).Find), ctx, spec)
}

// Get mocks base method.
func (m *MockNewsRepository) Get(ctx context.Context, spec specifications.I) (entity.News, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, spec)
	ret0, _ := ret[0].(entity.News)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNewsRepositoryMockRecorder) Get(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNewsRepository)(nil).Get), ctx, spec)
}

// Update mocks base method.
func (m *MockNewsRepository) Update(ctx context.Context, news *entity.News) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, news)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNewsRepositoryMockRecorder) Update(ctx, news any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNewsRepository)(nil).Update), ctx, news)
}
