// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_interface.go -source=interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	specifications "github.com/financial_advisor/app/domain/repository/specifications"
	gomock "go.uber.org/mock/gomock"
)

// MockI is a mock of I interface.
type MockI struct {
	ctrl     *gomock.Controller
	recorder *MockIMockRecorder
	isgomock struct{}
}

// MockIMockRecorder is the mock recorder for MockI.
type MockIMockRecorder struct {
	mock *MockI
}

// NewMockI creates a new mock instance.
func NewMockI(ctrl *gomock.Controller) *MockI {
	mock := &MockI{ctrl: ctrl}
	mock.recorder = &MockIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockI) EXPECT() *MockIMockRecorder {
	return m.recorder
}

// ToCount mocks base method.
func (m *MockI) ToCount() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToCount")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToCount indicates an expected call of ToCount.
func (mr *MockIMockRecorder) ToCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToCount", reflect.TypeOf((*MockI)(nil).ToCount))
}

// ToFind mocks base method.
func (m *MockI) ToFind(paging specifications.PagingI) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToFind", paging)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToFind indicates an expected call of ToFind.
func (mr *MockIMockRecorder) ToFind(paging any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToFind", reflect.TypeOf((*MockI)(nil).ToFind), paging)
}

// ToGet mocks base method.
func (m *MockI) ToGet() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToGet")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToGet indicates an expected call of ToGet.
func (mr *MockIMockRecorder) ToGet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToGet", reflect.TypeOf((*MockI)(nil).ToGet))
}

// MockPagingI is a mock of PagingI interface.
type MockPagingI struct {
	ctrl     *gomock.Controller
	recorder *MockPagingIMockRecorder
	isgomock struct{}
}

// MockPagingIMockRecorder is the mock recorder for MockPagingI.
type MockPagingIMockRecorder struct {
	mock *MockPagingI
}

// NewMockPagingI creates a new mock instance.
func NewMockPagingI(ctrl *gomock.Controller) *MockPagingI {
	mock := &MockPagingI{ctrl: ctrl}
	mock.recorder = &MockPagingIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPagingI) EXPECT() *MockPagingIMockRecorder {
	return m.recorder
}

// Limit mocks base method.
func (m *MockPagingI) Limit() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limit")
	ret0, _ := ret[0].(int)
	return ret0
}

// Limit indicates an expected call of Limit.
func (mr *MockPagingIMockRecorder) Limit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*MockPagingI)(nil).Limit))
}

// Offset mocks base method.
func (m *MockPagingI) Offset() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offset")
	ret0, _ := ret[0].(int)
	return ret0
}

// Offset indicates an expected call of Offset.
func (mr *MockPagingIMockRecorder) Offset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offset", reflect.TypeOf((*MockPagingI)(nil).Offset))
}
