searchd {
    listen = 0.0.0.0:9306:mysql
    listen = 0.0.0.0:9308:http
    log = /var/log/manticore/searchd.log
    pid_file = /run/manticore/searchd.pid
}


table news {
  type = rt
  path = /var/lib/manticore/news
  min_infix_len = 3
  rt_field = content
  rt_field = title
  rt_field = news_id
  stored_only_fields = news_id
}
