// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/financial_advisor/app/external/db/gorm"
	"github.com/financial_advisor/app/external/db/gorm/manticore"
	"github.com/financial_advisor/app/external/db/gorm/mysql"
	"github.com/financial_advisor/app/external/hasher"
	"github.com/financial_advisor/app/services/consumer"
	"github.com/financial_advisor/app/services/worker"
	"github.com/financial_advisor/app/usecases"
)

// Injectors from wire.go:

func InjectNewsFindUsecase() usecases.NewsFindUsecase {
	mySQL := gorm.GetMySQLIns()
	newsRepository := mysql.NewNewsRepository(mySQL)
	gormManticore := gorm.GetManticoreIns()
	newsWithFullTextRepository := manticore.NewNewsRepository(gormManticore)
	newsFindUsecase := usecases.NewNewsFindUsecase(newsRepository, newsWithFullTextRepository)
	return newsFindUsecase
}

func InjectPublishersFindUsecase() usecases.PublishersFindUsecase {
	mySQL := gorm.GetMySQLIns()
	publisherRepository := mysql.NewPublisherRepository(mySQL)
	publishersFindUsecase := usecases.NewPublishersFindUsecase(publisherRepository)
	return publishersFindUsecase
}

func InjectPublisherCreateUsecase() usecases.PublisherCreateUsecase {
	mySQL := gorm.GetMySQLIns()
	publisherRepository := mysql.NewPublisherRepository(mySQL)
	publisherCreateUsecase := usecases.NewPublisherCreateUsecase(publisherRepository)
	return publisherCreateUsecase
}

func InjectVnExpressScrapperUsecase() usecases.WebScrapperUsecase {
	mySQL := gorm.GetMySQLIns()
	newsRepository := mysql.NewNewsRepository(mySQL)
	gormManticore := gorm.GetManticoreIns()
	newsWithFullTextRepository := manticore.NewNewsRepository(gormManticore)
	webScrapperUsecase := usecases.NewVnExpressScrapperUsecase(newsRepository, newsWithFullTextRepository)
	return webScrapperUsecase
}

func InjectNewsCreateUsecase() usecases.NewsCreateUsecase {
	mySQL := gorm.GetMySQLIns()
	newsRepository := mysql.NewNewsRepository(mySQL)
	publisherRepository := mysql.NewPublisherRepository(mySQL)
	i := worker.Get()
	hasherI := hasher.NewMD5()
	newsCreateUsecase := usecases.NewNewsCreateUsecase(newsRepository, publisherRepository, i, hasherI)
	return newsCreateUsecase
}

func InjectNewsGetUsecase() usecases.NewsGetUsecase {
	mySQL := gorm.GetMySQLIns()
	newsRepository := mysql.NewNewsRepository(mySQL)
	gormManticore := gorm.GetManticoreIns()
	newsWithFullTextRepository := manticore.NewNewsRepository(gormManticore)
	newsGetUsecase := usecases.NewNewsGetUsecase(newsRepository, newsWithFullTextRepository)
	return newsGetUsecase
}

func InjectNewsDeleteUsecase() usecases.NewsDeleteUsecase {
	mySQL := gorm.GetMySQLIns()
	newsRepository := mysql.NewNewsRepository(mySQL)
	gormManticore := gorm.GetManticoreIns()
	newsWithFullTextRepository := manticore.NewNewsRepository(gormManticore)
	newsDeleteUsecase := usecases.NewNewsDeleteUsecase(newsRepository, newsWithFullTextRepository)
	return newsDeleteUsecase
}

func InjectPublisherGetUsecase() usecases.PublisherGetUsecase {
	mySQL := gorm.GetMySQLIns()
	publisherRepository := mysql.NewPublisherRepository(mySQL)
	publisherGetUsecase := usecases.NewPublisherGetUsecase(publisherRepository)
	return publisherGetUsecase
}

func InjectFallbackScrapperUsecase() usecases.FallbackScrapperUsecase {
	mySQL := gorm.GetMySQLIns()
	newsRepository := mysql.NewNewsRepository(mySQL)
	fallbackScrapperUsecase := usecases.NewFallbackScrapperUsecase(newsRepository)
	return fallbackScrapperUsecase
}

func InjectNewsSearchSuggestionGetUsecase() usecases.NewsSearchSuggestionsGetUsecase {
	gormManticore := gorm.GetManticoreIns()
	newsWithFullTextRepository := manticore.NewNewsRepository(gormManticore)
	newsSearchSuggestionsGetUsecase := usecases.NewNewsSearchSuggestionsGetUsecase(newsWithFullTextRepository)
	return newsSearchSuggestionsGetUsecase
}

func InjectNewsSearchUsecase() usecases.NewsSearchUsecase {
	mySQL := gorm.GetMySQLIns()
	newsRepository := mysql.NewNewsRepository(mySQL)
	gormManticore := gorm.GetManticoreIns()
	newsWithFullTextRepository := manticore.NewNewsRepository(gormManticore)
	newsSearchUsecase := usecases.NewNewsSearchUsecase(newsRepository, newsWithFullTextRepository)
	return newsSearchUsecase
}

func InjectConsumerService() consumer.I {
	v := ProvideProcessors()
	i := consumer.NewManager(v)
	return i
}
