// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_interface.go -source=interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFindHandler is a mock of FindHandler interface.
type MockFindHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFindHandlerMockRecorder
	isgomock struct{}
}

// MockFindHandlerMockRecorder is the mock recorder for MockFindHandler.
type MockFindHandlerMockRecorder struct {
	mock *MockFindHandler
}

// NewMockFindHandler creates a new mock instance.
func NewMockFindHandler(ctrl *gomock.Controller) *MockFindHandler {
	mock := &MockFindHandler{ctrl: ctrl}
	mock.recorder = &MockFindHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindHandler) EXPECT() *MockFindHandlerMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockFindHandler) Find(arg0 *http.Request) (any, any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find indicates an expected call of Find.
func (mr *MockFindHandlerMockRecorder) Find(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockFindHandler)(nil).Find), arg0)
}

// MockGetHandler is a mock of GetHandler interface.
type MockGetHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGetHandlerMockRecorder
	isgomock struct{}
}

// MockGetHandlerMockRecorder is the mock recorder for MockGetHandler.
type MockGetHandlerMockRecorder struct {
	mock *MockGetHandler
}

// NewMockGetHandler creates a new mock instance.
func NewMockGetHandler(ctrl *gomock.Controller) *MockGetHandler {
	mock := &MockGetHandler{ctrl: ctrl}
	mock.recorder = &MockGetHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetHandler) EXPECT() *MockGetHandlerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGetHandler) Get(arg0 *http.Request) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGetHandlerMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGetHandler)(nil).Get), arg0)
}

// MockCreateHandler is a mock of CreateHandler interface.
type MockCreateHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCreateHandlerMockRecorder
	isgomock struct{}
}

// MockCreateHandlerMockRecorder is the mock recorder for MockCreateHandler.
type MockCreateHandlerMockRecorder struct {
	mock *MockCreateHandler
}

// NewMockCreateHandler creates a new mock instance.
func NewMockCreateHandler(ctrl *gomock.Controller) *MockCreateHandler {
	mock := &MockCreateHandler{ctrl: ctrl}
	mock.recorder = &MockCreateHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateHandler) EXPECT() *MockCreateHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCreateHandler) Create(arg0 *http.Request) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCreateHandlerMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreateHandler)(nil).Create), arg0)
}

// MockDeleteHandler is a mock of DeleteHandler interface.
type MockDeleteHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteHandlerMockRecorder
	isgomock struct{}
}

// MockDeleteHandlerMockRecorder is the mock recorder for MockDeleteHandler.
type MockDeleteHandlerMockRecorder struct {
	mock *MockDeleteHandler
}

// NewMockDeleteHandler creates a new mock instance.
func NewMockDeleteHandler(ctrl *gomock.Controller) *MockDeleteHandler {
	mock := &MockDeleteHandler{ctrl: ctrl}
	mock.recorder = &MockDeleteHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteHandler) EXPECT() *MockDeleteHandlerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeleteHandler) Delete(arg0 *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeleteHandlerMockRecorder) Delete(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeleteHandler)(nil).Delete), arg0)
}
