// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_queue.go -source=queue.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	queue "github.com/financial_advisor/app/services/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockI is a mock of I interface.
type MockI struct {
	ctrl     *gomock.Controller
	recorder *MockIMockRecorder
	isgomock struct{}
}

// MockIMockRecorder is the mock recorder for MockI.
type MockIMockRecorder struct {
	mock *MockI
}

// NewMockI creates a new mock instance.
func NewMockI(ctrl *gomock.Controller) *MockI {
	mock := &MockI{ctrl: ctrl}
	mock.recorder = &MockIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockI) EXPECT() *MockIMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockI)(nil).Close))
}

// Enqueue mocks base method.
func (m *MockI) Enqueue(message queue.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockIMockRecorder) Enqueue(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockI)(nil).Enqueue), message)
}
