name: Deploy Search Engine

on:
  push:
    branches:
      - main

env:
  CONTAINER_NAME: financial-advisor-searchengine

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: 
      name: production # must follow rules set
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy config via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: manticore/manticore.conf
          target: /mnt/data
          overwrite: true
          
      - name: Reload search engine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Install Docker if not exists
            if ! command -v docker &> /dev/null; then
              sudo dnf update -y
              sudo dnf install -y docker
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user
              sudo newgrp docker
            fi

            # restart container to reflect new config
            docker restart ${{ env.CONTAINER_NAME }} || true

            sudo chown -R 999:999 /mnt/data/manticore

  deploy:
    runs-on: ubuntu-latest
    needs: migrate
    environment:
      name: production
    steps:
      - name: Deploy search engine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Install Docker if not exists
            if ! command -v docker &> /dev/null; then
              sudo dnf update -y
              sudo dnf install -y docker
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user
              sudo newgrp docker
            fi

            # Stop and remove old container
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            
            # restart container to reflect new config
            docker run -d --name ${{ env.CONTAINER_NAME }} \
              --mount type=bind,src=/mnt/data/manticore,dst=/var/lib/manticore \
              --mount type=bind,src=/mnt/data/manticore/manticore.conf,dst=/etc/manticoresearch/manticore.conf \
              --user manticore \
              --restart unless-stopped \
              -p 9306:9306 \
              -p 9308:9308 \
              manticoresearch/manticore

            sudo chown -R 999:999 /mnt/data/manticore
