name: Deployment flow

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: podron/financial-advisor
  CONTAINER_NAME: financial-advisor-server

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      TEST_RESULTS: /tmp/test-results
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install additional commands
        run: |
          go install github.com/jstemmer/go-junit-report@latest

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          make mod

      - name: Go test
        run: |
          make test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.TEST_RESULTS }}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.server -t financial-advisor:latest --platform="linux/amd64" . 
          docker tag financial-advisor:latest podron/financial-advisor:latest |
          docker build -f Dockerfile.migration -t financial-advisor-migrate:latest --platform="linux/amd64" .
          docker tag financial-advisor-migrate:latest podron/financial-advisor-migrate:latest

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push podron/financial-advisor:latest
          docker push podron/financial-advisor-migrate:latest

  migrate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Migrate schema
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Install Docker if not exists
            if ! command -v docker &> /dev/null; then
              sudo dnf update -y
              sudo dnf install -y docker
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user
              sudo newgrp docker
            fi

            docker pull podron/financial-advisor-migrate:latest

            # Migration
            container_output=$(
              docker run --rm \
                -e ENV=${{ secrets.ENV }} \
                -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
                -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
                -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
                -e MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
                -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} podron/financial-advisor-migrate:latest
            )

            echo "$container_output"

            if [[ ! "$container_output" == *"Applied"* ]]; then
              exit 2
            fi

            exit 0
  deploy:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Install Docker if not exists
            if ! command -v docker &> /dev/null; then
              sudo dnf update -y
              sudo dnf install -y docker
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user
              sudo newgrp docker
            fi

            # grant permission for user in container
            sudo chown -R 1000:1000 /mnt/data
            
            # Login to dockerhub
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull podron/financial-advisor:latest

            # Stop and remove old container
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true

            # Clean up old images
            docker image prune -f

            # Run new container
            sudo docker run -d --name ${{ env.CONTAINER_NAME }} \
              --mount type=bind,src=/mnt/data,dst=/app/data \
              -p ${{ secrets.HTTP_PORT }}:${{ secrets.HTTP_PORT }} \
              -e ENV=${{ secrets.ENV }}\
              -e HTTP_PORT=${{ secrets.HTTP_PORT }} \
              -e LOG_LEVEL=${{ secrets.LOG_LEVEL }} \
              -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
              -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
              -e MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
              -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
              -e CORS_ALLOWED_HOSTS=${{ secrets.CORS_ALLOWED_HOSTS }} \
              --restart unless-stopped \
              podron/financial-advisor:latest
            docker logout
